name: Testes Automatizados

on: [push]

jobs:
  testes:
    name: Testes BDD
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar ambiente Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Escolha a versão do Python que deseja usar

    - name: Instalar dependências
      run: pip install behave

    - name: Executar testes com Behave
      run: behave